# Nomeando os componentes do agente
agente_python.sources = sources_tail
agente_python.sinks = sink_kafka
agente_python.channels = canal_memoria

# Configuração da Source:
agente_python.sources.sources_tail.type = exec
agente_python.sources.sources_tail.command = tail -F /opt/flume/logs/app.log
agente_python.sources.sources_tail.restart = true

# Configuração do channel:
agente_python.channels.canal_memoria.type = memory
agente_python.channels.canal_memoria.capacity = 10000
agente_python.channels.canal_memoria.transactionCapacity = 100

# Configuração do sink Kafka:
agente_python.sinks.sink_kafka.type = org.apache.flume.sink.kafka.KafkaSink
agente_python.sinks.sink_kafka.kafka.bootstrap.servers = kafka:9092
agente_python.sinks.sink_kafka.topic = events
agente_python.sinks.sink_kafka.requiredAcks = 1
agente_python.sinks.sink_kafka.batchSize = 20

# Vinculação
agente_python.sources.sources_tail.channels = canal_memoria
agente_python.sinks.sink_kafka.channel = canal_memoria