# Nomeando os componentes do agente
agente_python.sources = sources_tail
agente_python.sinks = sink_logger
agente_python.channels = canal_memoria

#Configuração da Source: 
agente_python.sources.sources_tail.type = exec
agente_python.sources.sources_tail.command = tail -F /opt/flume/logs/app.log
agente_python.sources.sources_tail.restart = true

#Configuração do channel:
agente_python.channels.canal_memoria.type = memory
agente_python.channels.canal_memoria.capacity = 10000
agente_python.channels.canal_memoria.transactionCapacity = 100

#Configuração do sink:
agente_python.sinks.sink_logger.type = logger

#Vinculação
agente_python.sources.sources_tail.channels = canal_memoria
agente_python.sinks.sink_logger.channel = canal_memoria